// Extract captured on-device scene uploads (a3 streams) from btsnoop logs and
// emit web/captured-scenes.js so CloudGrid can replay them byte-for-byte. Each
// scene is the sequence of a3 chunks (a3 00 … a3 ff); the commit is re-added by
// the replay path, so it is not stored. Stores 19 leading bytes per chunk (the
// checksum is recomputed on send). De-dupes identical streams.
//
// Run: bun tools/extract-scenes.ts captures/<log> [more logs…]
import { readBtsnoop } from "./btsnoop.ts";

const files = process.argv.slice(2);
if (!files.length) { console.error("usage: bun tools/extract-scenes.ts <log> [log…]"); process.exit(1); }

const streams: number[][][] = [];
for (const f of files) {
  const writes = readBtsnoop(new Uint8Array(await Bun.file(f).arrayBuffer())).map((w) => w.value);
  let cur: number[][] | null = null;
  for (const v of writes) {
    if (v[0] !== 0xa3) continue;
    if (v[1] === 0x00) { if (cur) streams.push(cur); cur = []; }
    if (cur) cur.push(Array.from(v.slice(0, 19))); // 19-byte leading (no checksum)
    if (v[1] === 0xff && cur) { streams.push(cur); cur = null; }
  }
  if (cur) streams.push(cur);
}

// De-dupe identical streams, preserving first-seen order.
const seen = new Set<string>();
const uniq: number[][][] = [];
for (const s of streams) {
  const key = s.map((p) => p.join(",")).join("|");
  if (seen.has(key)) continue;
  seen.add(key);
  uniq.push(s);
}

// Curated labels (from playing each scene on the device), keyed by a stable
// header signature `type-speed-bright-bgR.bgG.bgB` so re-running the extractor
// keeps the names. Only the rich 0x02 animated scenes are kept; the 0x03
// DIY+effect streams were just the Clockwise effect on a scratch design.
const LABELS: Record<string, string> = {
  "5-41-0-0.0.1": "Universe",
  "1-32-0-0.0.5": "Amber glow",
  "2-29-0-0.0.1": "Blue-purple spin",
  "5-41-0-3.50.0": "Blue/white/pink",
  "5-29-16-0.0.1": "Green-purple spin",
  "1-29-0-0.0.1": "Blue-green gradient",
  "5-32-48-0.0.1": "Wave",
};
const sig = (p0: number[]) => `${p0[5]}-${p0[6]}-${p0[7]}-${p0[8]}.${p0[9]}.${p0[10]}`;
const scenes = uniq
  .filter((s) => s[0][4] === 0x02) // rich animated scenes only
  .map((s, i) => {
    const p0 = s[0];
    return { id: "s" + (i + 1), label: LABELS[sig(p0)] || `Scene ${i + 1} (type${p0[5]} · ${s.length}p)`, fmt: p0[4], type: p0[5], pkts: s };
  });

const out =
  "// GENERATED by tools/extract-scenes.ts from official-app BLE captures.\n" +
  "// Each scene is a captured on-device-animation upload, replayed verbatim.\n" +
  "// pkts = a3 chunks (19 leading bytes each); the commit is re-added on send.\n" +
  "window.CG_SCENES = " + JSON.stringify(scenes) + ";\n";
await Bun.write("web/captured-scenes.js", out);
console.log(`Wrote web/captured-scenes.js with ${scenes.length} scene(s):`);
for (const sc of scenes) console.log(`  ${sc.id}  fmt=0x0${sc.fmt} type=0x0${sc.type.toString(16)} ${sc.pkts.length} pkts`);
